# Title

An short introduction about PyTorch and about the chosen functions. 

- torch.zeros
- torch.eye
- torch.ones
- torch.rand
- torch.unsqueeze

Before we begin, let's install and import PyTorch

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros

Return tensor with zeros in rows and columns

In [ ]:
# Example 1 - working (change this)
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

A 2-by-2 tensor having all enties as 0

In [ ]:
# Example 2 - working
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

3-by-4 tensor containg zeros at each position

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.zeros()

TypeError: ignored

Tensor of zeros with no defined rows and columns of tensor

This function is used to generate an empty tensor or tensor containing only zeros

## Function 2 - torch.eye

Identity tensor is same like identity matrix having 1's in diagonal and 0's in other places.

In [ ]:
# Example 1 - working
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

Identity tensor having 2 rows and 2 columns

In [ ]:
# Example 2 - working
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Identity tensor having 3 rows and 3 columns

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.eye()

TypeError: ignored

Identity tensor with no rows and columns

This function is used to make identity matrixes/tensors used in computations with other tensors/matrixes

## Function 3 - torch.ones

torch.ones is used to generate tensor containig 1's in each row and column

In [ ]:
# Example 1 - working
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

a 2-by-2 tensor containing 1's in rows and columns

In [ ]:
# Example 2 - working
torch.ones(5,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

a tensor containing 5 row and 6 columns having 1's as their value

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.ones(-1,-1)

RuntimeError: ignored

It will break when negative dimensions will be given

tensor.ones is used to genarate tensor containing 1's only in positive dimensions

## Function 4 - torch.rand

tensor.rand to generate random valued tensor

In [ ]:
# Example 1 - working
torch.rand(2,2,3)

tensor([[[0.1155, 0.0887, 0.0104],
         [0.3744, 0.0880, 0.8686]],

        [[0.0238, 0.2649, 0.4369],
         [0.7549, 0.5351, 0.9361]]])

A three dimensional tensor to generate random values at every index

In [ ]:
# Example 2 - working
torch.rand(3,4)

tensor([[0.0389, 0.2987, 0.3474, 0.4845],
        [0.5246, 0.1928, 0.2899, 0.3602],
        [0.7553, 0.0021, 0.8936, 0.7167]])

3-by-4 size tensor containing random numbers 

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.rand()

TypeError: ignored

It will break when no tensor dimensions or size will be given

This function is used to generate random values containing tensors

## Function 5 - torch.unsqueeze

Returns a new tensor with a dimension of size one inserted at the specified position.

In [ ]:
# Example 1 - working
x=torch.tensor([1,2,3,4])
torch.unsqueeze(x,0)

tensor([[1, 2, 3, 4]])

Unsqueezing x at 0

In [ ]:
# Example 2 - working
torch.unsqueeze(x,1)

tensor([[1],
        [2],
        [3],
        [4]])

unsqueeze at 1

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.unsqueeze(x,2)

IndexError: ignored

It will break if dimension given is out of range

this function is used to unsqueezing a tensor at any dimension

## Conclusion

We studied different tensor functions in order to enhance our knowledge about tensors. We studied about usage of tensor and its functions. 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* https://medium.com/secure-and-private-ai-writing-challenge/introduction-to-tensors-2-using-pytorch-2b6270a838f